// test/community-fixtures.test.mjs
//
// AUTO-GENERATED by `groundtruth fixture add`. Do not edit by hand.
// Each line in test/fixtures/community-false-positives.txt should produce
// zero claims. Each line in community-true-positives.txt should produce
// at least one. This file is regenerated when fixtures are added.

import { test } from "node:test";
import { strictEqual, ok } from "node:assert";
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { detectClaims } from "../src/detector.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FALSE = join(__dirname, "fixtures", "community-false-positives.txt");
const TRUE = join(__dirname, "fixtures", "community-true-positives.txt");

function readLines(path) {
  if (!existsSync(path)) return [];
  return readFileSync(path, "utf8")
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith("#"));
}

for (const sentence of readLines(FALSE)) {
  test(`community false-positive: "${sentence.slice(0, 70)}${sentence.length > 70 ? '…' : ''}" must produce 0 claims`, () => {
    strictEqual(detectClaims(sentence).length, 0, `detector fired on: ${sentence}`);
  });
}

for (const sentence of readLines(TRUE)) {
  test(`community true-positive: "${sentence.slice(0, 70)}${sentence.length > 70 ? '…' : ''}" must produce >= 1 claim`, () => {
    ok(detectClaims(sentence).length >= 1, `detector missed: ${sentence}`);
  });
}
