// src/fixture-add.mjs
//
// `groundtruth fixture add <sentence>` — turns a real false-positive
// report into a fixture in one command. Closes the contribution loop:
// when a user pastes a sentence the detector wrongly flagged, this
// captures it permanently so future regressions are caught by `node --test`.
//
// Usage:
//   groundtruth fixture add "The team is ready for the demo."
//   groundtruth fixture add --positive "I've implemented the parser."
//
// What it does:
//   1. Runs the sentence through detectClaims to confirm what the detector
//      currently does with it.
//   2. Appends a one-line entry to test/fixtures/community-false-positives.txt
//      (or community-true-positives.txt if --positive).
//   3. Updates a generated test file test/community-fixtures.test.mjs that
//      exercises every line in those text files.
//
// The result is a single command that converts "this fired wrongly" into
// a permanent regression test.

import { existsSync, readFileSync, writeFileSync, appendFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { detectClaims } from "./detector.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = dirname(__dirname);
const FIXTURES_DIR = join(REPO_ROOT, "test", "fixtures");
const FALSE_POSITIVES_FILE = join(FIXTURES_DIR, "community-false-positives.txt");
const TRUE_POSITIVES_FILE = join(FIXTURES_DIR, "community-true-positives.txt");
const TEST_FILE = join(REPO_ROOT, "test", "community-fixtures.test.mjs");

const TEST_TEMPLATE = `// test/community-fixtures.test.mjs
//
// AUTO-GENERATED by \`groundtruth fixture add\`. Do not edit by hand.
// Each line in test/fixtures/community-false-positives.txt should produce
// zero claims. Each line in community-true-positives.txt should produce
// at least one. This file is regenerated when fixtures are added.

import { test } from "node:test";
import { strictEqual, ok } from "node:assert";
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { detectClaims } from "../src/detector.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FALSE = join(__dirname, "fixtures", "community-false-positives.txt");
const TRUE = join(__dirname, "fixtures", "community-true-positives.txt");

function readLines(path) {
  if (!existsSync(path)) return [];
  return readFileSync(path, "utf8")
    .split("\\n")
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith("#"));
}

for (const sentence of readLines(FALSE)) {
  test(\`community false-positive: "\${sentence.slice(0, 70)}\${sentence.length > 70 ? '…' : ''}" must produce 0 claims\`, () => {
    strictEqual(detectClaims(sentence).length, 0, \`detector fired on: \${sentence}\`);
  });
}

for (const sentence of readLines(TRUE)) {
  test(\`community true-positive: "\${sentence.slice(0, 70)}\${sentence.length > 70 ? '…' : ''}" must produce >= 1 claim\`, () => {
    ok(detectClaims(sentence).length >= 1, \`detector missed: \${sentence}\`);
  });
}
`;

function ensureFixturesDir() {
  if (!existsSync(FIXTURES_DIR)) mkdirSync(FIXTURES_DIR, { recursive: true });
}

function ensureTestFileExists() {
  if (!existsSync(TEST_FILE)) writeFileSync(TEST_FILE, TEST_TEMPLATE);
}

function appendUnique(file, line) {
  if (!existsSync(file)) writeFileSync(file, "# Community-contributed sentences. One per line. Lines starting with # are comments.\n");
  const existing = readFileSync(file, "utf8")
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean);
  if (existing.includes(line)) return false;
  appendFileSync(file, `${line}\n`);
  return true;
}

export async function runFixtureAdd(args) {
  let positive = false;
  const positional = [];
  for (const a of args) {
    if (a === "--positive" || a === "-p") positive = true;
    else if (a === "--negative" || a === "-n") positive = false;
    else if (!a.startsWith("--")) positional.push(a);
  }
  if (positional.length === 0) {
    process.stderr.write(
      "groundtruth fixture add: provide the sentence to capture as a fixture.\n" +
        "  groundtruth fixture add \"The team is ready for the demo.\"\n" +
        "  groundtruth fixture add --positive \"I've implemented the parser.\"\n",
    );
    process.exit(2);
  }
  const sentence = positional.join(" ").trim();
  if (sentence.length < 4) {
    process.stderr.write("groundtruth fixture add: sentence too short.\n");
    process.exit(2);
  }

  // First, show what the detector currently does with this sentence.
  const claims = detectClaims(sentence);
  process.stdout.write(`groundtruth fixture add\n\n`);
  process.stdout.write(`  sentence: "${sentence}"\n`);
  process.stdout.write(`  category: ${positive ? "true-positive (should fire)" : "false-positive (should NOT fire)"}\n`);
  process.stdout.write(`  detector currently produces: ${claims.length} claim(s)\n`);
  if (claims.length > 0) {
    for (const c of claims) {
      process.stdout.write(`    - pattern: ${c.pattern}, trigger: ${c.word}, match: "${c.match}"\n`);
    }
  }
  process.stdout.write("\n");

  // Sanity check: the report should contradict current behavior, otherwise
  // there's nothing to fix.
  if (positive && claims.length > 0) {
    process.stdout.write("  note: detector ALREADY catches this. Adding as a regression guard anyway.\n");
  }
  if (!positive && claims.length === 0) {
    process.stdout.write("  note: detector ALREADY ignores this. Adding as a regression guard anyway.\n");
  }

  ensureFixturesDir();
  ensureTestFileExists();
  const target = positive ? TRUE_POSITIVES_FILE : FALSE_POSITIVES_FILE;
  const added = appendUnique(target, sentence);
  if (!added) {
    process.stdout.write(`  already in ${target}; nothing to add.\n`);
    process.exit(0);
  }
  process.stdout.write(`  appended to ${target}\n`);
  process.stdout.write(`  test/community-fixtures.test.mjs will pick it up automatically on next \`node --test\`\n`);
  process.stdout.write("\n");
  process.stdout.write("Next: open a PR with the new fixture line and a regex exclusion in src/detector.mjs if needed.\n");
  process.exit(0);
}
